[package]
name = "effitask"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
homepage = "https://github.com/sanpii/effitask"

[dependencies]
cairo-rs = "^0.5"
chrono = "^0.4"
gdk = "^0.9"
gdk-sys = "^0.7"
glib = "^0.6"
human-panic = "^1.0"
pulldown-cmark = "^0.2"
rand = "^0.6"
regex = "^1.0"
relm = "^0.15"
relm-attributes = "^0.15"
relm-derive = "^0.15"
xdg = "^2.1"

[dependencies.gtk]
version = "0.5"
features = ["v3_22"]

[dependencies.log]
version = "^0.4"
features = ["std"]

[dependencies.todo-txt]
version = "^1.2"
features = ["extended"]

[features]
default = ["relm/unstable", "relm-attributes/unstable", "relm-derive/unstable"]

[badges]
gitlab = { repository = "sanpi/effitask", branch = "master" }
