[package]
name = "effitask"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
homepage = "https://github.com/sanpii/effitask"
edition = "2018"

[dependencies]
cairo-rs = "^0.8"
chrono = "^0.4"
dotenv = "0.15"
dirs-sys = "^0.3"
gdk = "^0.12"
gdk-sys = "^0.9"
glib = "^0.9"
human-panic = "^1.0"
lazy_static = "^1.4"
notify = "^4.0"
pulldown-cmark = "0.7"
rand = "^0.7"
regex = "^1.0"
relm = "^0.19"
relm-derive = "^0.19"
xdg = "2.1"

[dependencies.gtk]
version = "0.8"
features = ["v3_22"]

[dependencies.log]
version = "^0.4"
features = ["std"]

[dependencies.todo-txt]
version = "^1.2"
features = ["extended"]

[badges]
gitlab = { repository = "sanpi/effitask", branch = "master" }
